-- AlterTable
ALTER TABLE `Map` ADD COLUMN `lat1` DECIMAL(10, 8) NULL,
    ADD COLUMN `lat2` DECIMAL(10, 8) NULL,
    ADD COLUMN `lng1` DECIMAL(11, 8) NULL,
    ADD COLUMN `lng2` DECIMAL(11, 8) NULL;
